// Hand-written FFI for the `mnn_c/` C wrapper layer.
//
// Previously generated by bindgen at build time; checked in to avoid libclang
// during cross-compilation (especially Android on Windows hosts).

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ErrorCode {
    ERROR_CODE_NO_ERROR = 0,
    ERROR_CODE_OUT_OF_MEMORY = 1,
    ERROR_CODE_NOT_SUPPORT = 2,
    ERROR_CODE_COMPUTE_SIZE_ERROR = 3,
    ERROR_CODE_NO_EXECUTION = 4,
    ERROR_CODE_INVALID_VALUE = 5,
    ERROR_CODE_INPUT_DATA_ERROR = 10,
    ERROR_CODE_CALL_BACK_STOP = 11,
    ERROR_CODE_TENSOR_NOT_SUPPORT = 20,
    ERROR_CODE_TENSOR_NEED_DIVIDE = 21,
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MNNForwardType {
    MNN_FORWARD_CPU = 0,
    MNN_FORWARD_AUTO = 4,
    MNN_FORWARD_METAL = 1,
    MNN_FORWARD_CUDA = 2,
    MNN_FORWARD_OPENCL = 3,
    MNN_FORWARD_OPENGL = 6,
    MNN_FORWARD_VULKAN = 7,
    MNN_FORWARD_NN = 5,
    MNN_FORWARD_USER_0 = 8,
    MNN_FORWARD_USER_1 = 9,
    MNN_FORWARD_USER_2 = 10,
    MNN_FORWARD_USER_3 = 11,
    MNN_FORWARD_ALL = 12,
    MNN_FORWARD_CPU_EXTENSION = 13,
    MNN_MEMORY_AHARDWAREBUFFER = 14,
    MNN_CONVERT_QNN = 32,
    MNN_CONVERT_NEUROPILOT = 33,
    MNN_CONVERT_COREML = 34,
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MNNGpuMode {
    MNN_GPU_TUNING_NONE = 1,
    MNN_GPU_TUNING_HEAVY = 2,
    MNN_GPU_TUNING_WIDE = 4,
    MNN_GPU_TUNING_NORMAL = 8,
    MNN_GPU_TUNING_FAST = 16,
    MNN_GPU_MEMORY_BUFFER = 64,
    MNN_GPU_MEMORY_IMAGE = 128,
    MNN_GPU_RECORD_OP = 256,
    MNN_GPU_RECORD_BATCH = 512,
}

impl MemoryMode {
    pub const Memory_Normal: MemoryMode = MemoryMode(0);
    pub const Memory_High: MemoryMode = MemoryMode(1);
    pub const Memory_Low: MemoryMode = MemoryMode(2);
}

#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct MemoryMode(pub core::ffi::c_int);

impl PowerMode {
    pub const Power_Normal: PowerMode = PowerMode(0);
    pub const Power_High: PowerMode = PowerMode(1);
    pub const Power_Low: PowerMode = PowerMode(2);
}

#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PowerMode(pub core::ffi::c_int);

impl PrecisionMode {
    pub const Precision_Normal: PrecisionMode = PrecisionMode(0);
    pub const Precision_High: PrecisionMode = PrecisionMode(1);
    pub const Precision_Low: PrecisionMode = PrecisionMode(2);
    pub const Precision_Low_BF16: PrecisionMode = PrecisionMode(3);
}

#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PrecisionMode(pub core::ffi::c_int);

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MNNBackendConfig {
    _unused: [u8; 0],
}

unsafe extern "C" {
    pub fn mnnbc_create() -> *mut MNNBackendConfig;
    pub fn mnnbc_clone(config: *const MNNBackendConfig) -> *mut MNNBackendConfig;
    pub fn mnnbc_destroy(config: *mut MNNBackendConfig);
    pub fn mnnbc_set_memory_mode(config: *mut MNNBackendConfig, memory_mode: MemoryMode);
    pub fn mnnbc_set_power_mode(config: *mut MNNBackendConfig, power_mode: PowerMode);
    pub fn mnnbc_set_precision_mode(config: *mut MNNBackendConfig, precision_mode: PrecisionMode);
    pub fn mnnbc_set_shared_context(
        config: *mut MNNBackendConfig,
        shared_context: *mut core::ffi::c_void,
    );
    pub fn mnnbc_set_flags(config: *mut MNNBackendConfig, flags: usize);
    pub fn mnnbc_reset(config: *mut MNNBackendConfig);
    pub fn mnnbc_get_memory_mode(config: *mut MNNBackendConfig) -> MemoryMode;
    pub fn mnnbc_get_power_mode(config: *mut MNNBackendConfig) -> PowerMode;
    pub fn mnnbc_get_precision_mode(config: *mut MNNBackendConfig) -> PrecisionMode;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MNNScheduleConfig {
    _unused: [u8; 0],
}

unsafe extern "C" {
    pub fn mnnsc_create() -> *mut MNNScheduleConfig;
    pub fn mnnsc_clone(from: *const MNNScheduleConfig) -> *mut MNNScheduleConfig;
    pub fn mnnsc_destroy(config: *mut MNNScheduleConfig);
    pub fn mnnsc_set_save_tensors(
        config: *mut MNNScheduleConfig,
        saveTensors: *const *const core::ffi::c_char,
        saveTensorsSize: usize,
    );
    pub fn mnnsc_set_type(config: *mut MNNScheduleConfig, type_: MNNForwardType);
    pub fn mnnsc_set_num_threads(config: *mut MNNScheduleConfig, numThread: core::ffi::c_int);
    pub fn mnnsc_set_mode(config: *mut MNNScheduleConfig, mode: core::ffi::c_int);
    pub fn mnnsc_set_backup_type(config: *mut MNNScheduleConfig, backupType: MNNForwardType);
    pub fn mnnsc_set_backend_config(
        config: *mut MNNScheduleConfig,
        backendConfig: *mut MNNBackendConfig,
    );
    pub fn mnnsc_get_type(config: *mut MNNScheduleConfig) -> MNNForwardType;
    pub fn mnnsc_get_backup_type(config: *mut MNNScheduleConfig) -> MNNForwardType;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Session {
    _unused: [u8; 0],
}

unsafe extern "C" {
    pub fn Session_destroy(session: *mut Session);
    pub fn Session_hasAsyncWork(session: *mut Session) -> core::ffi::c_int;
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum halide_type_code_t {
    halide_type_int = 0,
    halide_type_uint = 1,
    halide_type_float = 2,
    halide_type_handle = 3,
    halide_type_bfloat = 4,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct halide_type_t {
    pub code: halide_type_code_t,
    pub bits: u8,
    pub lanes: u16,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct halide_device_interface_impl_t {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct halide_device_interface_t {
    pub device_malloc: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
            device_interface: *const halide_device_interface_t,
        ) -> core::ffi::c_int,
    >,
    pub device_free: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub device_sync: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub device_release: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            device_interface: *const halide_device_interface_t,
        ),
    >,
    pub copy_to_host: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub copy_to_device: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
            device_interface: *const halide_device_interface_t,
        ) -> core::ffi::c_int,
    >,
    pub device_and_host_malloc: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
            device_interface: *const halide_device_interface_t,
        ) -> core::ffi::c_int,
    >,
    pub device_and_host_free: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub buffer_copy: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            src: *mut halide_buffer_t,
            dst_device_interface: *const halide_device_interface_t,
            dst: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub device_crop: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            src: *const halide_buffer_t,
            dst: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub device_release_crop: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub wrap_native: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
            handle: u64,
            device_interface: *const halide_device_interface_t,
        ) -> core::ffi::c_int,
    >,
    pub detach_native: Option<
        unsafe extern "C" fn(
            user_context: *mut core::ffi::c_void,
            buf: *mut halide_buffer_t,
        ) -> core::ffi::c_int,
    >,
    pub impl_: *const halide_device_interface_impl_t,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct halide_dimension_t {
    pub min: i32,
    pub extent: i32,
    pub stride: i32,
    pub flags: u32,
}

pub const halide_buffer_flags_halide_buffer_flag_host_dirty: halide_buffer_flags = 1;
pub const halide_buffer_flags_halide_buffer_flag_device_dirty: halide_buffer_flags = 2;
pub type halide_buffer_flags = core::ffi::c_int;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct halide_buffer_t {
    pub device: u64,
    pub device_interface: *const halide_device_interface_t,
    pub host: *mut u8,
    pub flags: u64,
    pub type_: halide_type_t,
    pub dimensions: i32,
    pub dim: *mut halide_dimension_t,
    pub padding: *mut core::ffi::c_void,
}

#[repr(C)]
#[derive(Debug)]
pub struct CString {
    pub data: *mut core::ffi::c_char,
    pub size: usize,
}

unsafe extern "C" {
    pub fn createCString(data: *const core::ffi::c_char, size: usize) -> CString;
    pub fn destroyCString(string: *mut CString);
}

#[repr(C)]
#[derive(Debug)]
pub struct TensorInfo {
    pub name: CString,
    pub tensor: *mut core::ffi::c_void,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TensorInfoArray {
    pub tensors: *mut TensorInfo,
    pub size: usize,
}

unsafe extern "C" {
    pub fn createTensorInfoArray(count: usize) -> *mut TensorInfoArray;
    pub fn destroyTensorInfoArray(array: *mut TensorInfoArray);
    pub fn getTensorInfoArray(array: *const TensorInfoArray, index: usize) -> *mut TensorInfo;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Tensor {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TensorShape {
    pub shape: [core::ffi::c_int; 4],
    pub size: usize,
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum DimensionType {
    TENSORFLOW = 0,
    CAFFE = 1,
    CAFFE_C4 = 2,
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum HandleDataType {
    HANDLE_NONE = 0,
    HANDLE_STRING = 1,
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MapType {
    MAP_TENSOR_WRITE = 0,
    MAP_TENSOR_READ = 1,
}

unsafe extern "C" {
    pub fn Tensor_create(dimSize: core::ffi::c_int, type_: DimensionType) -> *mut Tensor;
    pub fn Tensor_createFromTensor(
        tensor: *const Tensor,
        type_: DimensionType,
        allocMemory: core::ffi::c_int,
    ) -> *mut Tensor;
    pub fn Tensor_destroy(tensor: *mut Tensor);
    pub fn Tensor_createDevice(
        shape: *const core::ffi::c_int,
        shapeSize: usize,
        typeCode: halide_type_t,
        dimType: DimensionType,
    ) -> *mut Tensor;
    pub fn Tensor_createWith(
        shape: *const core::ffi::c_int,
        shapeSize: usize,
        typeCode: halide_type_t,
        data: *mut core::ffi::c_void,
        dimType: DimensionType,
    ) -> *mut Tensor;
    pub fn Tensor_copyFromHostTensor(
        deviceTensor: *mut Tensor,
        hostTensor: *const Tensor,
    ) -> core::ffi::c_int;
    pub fn Tensor_copyToHostTensor(
        deviceTensor: *const Tensor,
        hostTensor: *mut Tensor,
    ) -> core::ffi::c_int;
    pub fn Tensor_createHostTensorFromDevice(
        deviceTensor: *const Tensor,
        copyData: core::ffi::c_int,
    ) -> *mut Tensor;
    pub fn Tensor_getDimensionType(tensor: *const Tensor) -> DimensionType;
    pub fn Tensor_buffer(tensor: *const Tensor) -> *const halide_buffer_t;
    pub fn Tensor_buffer_mut(tensor: *mut Tensor) -> *mut halide_buffer_t;
    pub fn Tensor_host(tensor: *const Tensor) -> *const core::ffi::c_void;
    pub fn Tensor_host_mut(tensor: *mut Tensor) -> *mut core::ffi::c_void;
    pub fn Tensor_deviceId(tensor: *const Tensor) -> u64;
    pub fn Tensor_dimensions(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_shape(tensor: *const Tensor) -> TensorShape;
    pub fn Tensor_size(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_usize(tensor: *const Tensor) -> usize;
    pub fn Tensor_elementSize(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_width(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_height(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_channel(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_batch(tensor: *const Tensor) -> core::ffi::c_int;
    pub fn Tensor_stride(tensor: *const Tensor, index: core::ffi::c_int) -> core::ffi::c_int;
    pub fn Tensor_length(tensor: *const Tensor, index: core::ffi::c_int) -> core::ffi::c_int;
    pub fn Tensor_setStride(tensor: *mut Tensor, index: core::ffi::c_int, stride: core::ffi::c_int);
    pub fn Tensor_setLength(tensor: *mut Tensor, index: core::ffi::c_int, length: core::ffi::c_int);
    pub fn Tensor_getDeviceInfo(
        tensor: *const Tensor,
        dst: *mut core::ffi::c_void,
        forwardType: core::ffi::c_int,
    ) -> core::ffi::c_int;
    pub fn Tensor_print(tensor: *const Tensor);
    pub fn Tensor_printShape(tensor: *const Tensor);
    pub fn Tensor_map(
        tensor: *mut Tensor,
        mtype: MapType,
        dtype: DimensionType,
    ) -> *mut core::ffi::c_void;
    pub fn Tensor_unmap(
        tensor: *mut Tensor,
        mtype: MapType,
        dtype: DimensionType,
        mapPtr: *mut core::ffi::c_void,
    );
    pub fn Tensor_clone(tensor: *const Tensor) -> *mut Tensor;
    pub fn Tensor_wait(
        tensor: *mut Tensor,
        mtype: MapType,
        finish: core::ffi::c_int,
    ) -> core::ffi::c_int;
    pub fn Tensor_setDevicePtr(
        tensor: *mut Tensor,
        devicePtr: *const core::ffi::c_void,
        memoryType: core::ffi::c_int,
    ) -> core::ffi::c_int;
    pub fn Tensor_getType(tensor: *const Tensor) -> halide_type_t;
    pub fn Tensor_isTypeOf(tensor: *const Tensor, type_: halide_type_t) -> bool;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Interpreter {
    _unused: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Backend {
    _unused: [u8; 0],
}

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum RuntimeStatus {
    STATUS_SUPPORT_FP16 = 0,
    STATUS_SUPPORT_DOT_PRODUCT = 1,
    STATUS_SUPPORT_POWER_LOW = 2,
    STATUS_COUNT = 3,
}

unsafe extern "C" {
    pub fn modelPrintIO(model: *const core::ffi::c_char);
    pub fn getVersion() -> *const core::ffi::c_char;
    pub fn Interpreter_createFromFile(file: *const core::ffi::c_char) -> *mut Interpreter;
    pub fn Interpreter_createFromBuffer(
        buffer: *const core::ffi::c_void,
        size: usize,
    ) -> *mut Interpreter;
    pub fn Interpreter_destroy(interpreter: *mut Interpreter);
}

pub mod SessionMode {
    #[cfg(windows)]
    pub type Type = core::ffi::c_int;
    #[cfg(not(windows))]
    pub type Type = u32;

    pub const Session_Debug: Type = 0;
    pub const Session_Release: Type = 1;
    pub const Session_Input_Inside: Type = 2;
    pub const Session_Input_User: Type = 3;
    pub const Session_Output_Inside: Type = 4;
    pub const Session_Output_User: Type = 5;
    pub const Session_Resize_Direct: Type = 6;
    pub const Session_Resize_Defer: Type = 7;
    pub const Session_Backend_Fix: Type = 8;
    pub const Session_Backend_Auto: Type = 9;
    pub const Session_Memory_Collect: Type = 10;
    pub const Session_Memory_Cache: Type = 11;
    pub const Session_Codegen_Disable: Type = 12;
    pub const Session_Codegen_Enable: Type = 13;
    pub const Session_Resize_Check: Type = 14;
    pub const Session_Resize_Fix: Type = 15;
}

unsafe extern "C" {
    pub fn Interpreter_setSessionMode(interpreter: *mut Interpreter, mode: SessionMode::Type);
    pub fn Interpreter_setCacheFile(
        interpreter: *mut Interpreter,
        cacheFile: *const core::ffi::c_char,
        keySize: usize,
    );
    pub fn Interpreter_setExternalFile(
        interpreter: *mut Interpreter,
        file: *const core::ffi::c_char,
        flag: usize,
    );
    pub fn Interpreter_updateCacheFile(
        interpreter: *mut Interpreter,
        session: *mut Session,
    ) -> ErrorCode;
    pub fn Interpreter_setSessionHint(
        interpreter: *mut Interpreter,
        mode: core::ffi::c_int,
        value: core::ffi::c_int,
    );
    pub fn Interpreter_createSession(
        interpreter: *mut Interpreter,
        config: *const MNNScheduleConfig,
    ) -> *mut Session;
    pub fn Interpreter_createMultiPathSession(
        interpreter: *mut Interpreter,
        configs: *const *const MNNScheduleConfig,
        configSize: usize,
    ) -> *mut Session;
    pub fn Interpreter_releaseSession(
        interpreter: *mut Interpreter,
        session: *mut Session,
    ) -> core::ffi::c_int;
    pub fn Interpreter_resizeSession(interpreter: *mut Interpreter, session: *mut Session);
    pub fn Interpreter_resizeSessionWithFlag(
        interpreter: *mut Interpreter,
        session: *mut Session,
        needRelloc: core::ffi::c_int,
    );
    pub fn Interpreter_releaseModel(interpreter: *mut Interpreter);
    pub fn Interpreter_getModelVersion(interpreter: *const Interpreter)
    -> *const core::ffi::c_char;
    pub fn Interpreter_updateSessionToModel(
        interpreter: *mut Interpreter,
        session: *mut Session,
    ) -> ErrorCode;
    pub fn Interpreter_runSession(
        interpreter: *const Interpreter,
        session: *mut Session,
    ) -> ErrorCode;
    pub fn Interpreter_runSessionWithCallBackInfo(
        interpreter: *const Interpreter,
        session: *const Session,
        before: *mut core::ffi::c_void,
        end: *mut core::ffi::c_void,
        sync: core::ffi::c_int,
    ) -> ErrorCode;
    pub fn Interpreter_getSessionInput(
        interpreter: *mut Interpreter,
        session: *const Session,
        name: *const core::ffi::c_char,
    ) -> *mut Tensor;
    pub fn Interpreter_getSessionOutput(
        interpreter: *mut Interpreter,
        session: *const Session,
        name: *const core::ffi::c_char,
    ) -> *mut Tensor;
    pub fn Interpreter_getSessionInfo(
        interpreter: *mut Interpreter,
        session: *const Session,
        code: core::ffi::c_int,
        ptr: *mut core::ffi::c_void,
    ) -> core::ffi::c_int;
    pub fn Interpreter_getSessionOutputAll(
        interpreter: *const Interpreter,
        session: *const Session,
    ) -> *const TensorInfoArray;
    pub fn Interpreter_getSessionInputAll(
        interpreter: *const Interpreter,
        session: *const Session,
    ) -> *const TensorInfoArray;
    pub fn Interpreter_resizeTensor(
        interpreter: *mut Interpreter,
        tensor: *mut Tensor,
        dims: *const core::ffi::c_int,
        dimsSize: usize,
    );
    pub fn Interpreter_resizeTensorByNCHW(
        interpreter: *mut Interpreter,
        tensor: *mut Tensor,
        batch: core::ffi::c_int,
        channel: core::ffi::c_int,
        height: core::ffi::c_int,
        width: core::ffi::c_int,
    );
    pub fn Interpreter_getBackend(
        interpreter: *const Interpreter,
        session: *const Session,
        tensor: *const Tensor,
    ) -> *const Backend;
    pub fn Interpreter_bizCode(interpreter: *const Interpreter) -> *const core::ffi::c_char;
    pub fn Interpreter_uuid(interpreter: *const Interpreter) -> *const core::ffi::c_char;
    pub fn OperatorInfo_name(op: *const core::ffi::c_void) -> *const core::ffi::c_char;
    pub fn OperatorInfo_type(op: *const core::ffi::c_void) -> *const core::ffi::c_char;
    pub fn OperatorInfo_flops(op: *const core::ffi::c_void) -> f32;
}
